name: main

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Yarn Cache Dir
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Yarn Install
        run: yarn install 
      - name: Run Tests
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: yarn test
      - name: Cache Node Modules
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Cache VSCode
        uses: actions/cache@v1
        with:
          path: .vscode-test
          key: ${{ runner.os }}-vscode-${{ hashFiles('.vscode-test') }}
          restore-keys: |
            ${{ runner.os }}-vscode-
